import { Permanent_Marker } from "next/font/google";
import { VT323 } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";
import Header from "@/components/header/Header";
import { ContactDialog } from "@/components/contactDialog/ContactDialog";
import Footer from "@/components/footer/Footer";

const vt323 = VT323({
  weight: "400",
  subsets: ["latin"],
  variable: "--font-vt323",
});

const permanentMarker = Permanent_Marker({
  weight: "400",
  subsets: ["latin"],
  variable: "--font-permanent-marker",
});

const orkney = localFont({
  src: "/fonts/Orkney Regular.woff",
  variable: "--font-orkney",
});

export const metadata = {
  title: "RSAY | رساي",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={` ${orkney.variable} ${vt323.variable} ${permanentMarker.variable} antialiased`}
      >
        <Header />
        {children}
        <Footer />
        <div className="fixed right-0 top-[50%] hover:scale-110 duration-300 z-20 shadow-md border rounded-s-xl overflow-hidden">
          <ContactDialog />
        </div>
      </body>
    </html>
  );
}
